dist: trusty
os: linux
language: node_js
node_js:
  - "8"
cache:
directories:
  - "node_modules"
before_install:
  # - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  # - echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
  # - sudo apt-get update
  # - sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono wine1.8 gcc-multilib g++-multilib
script: 
  - npm update -g npm
  - cd angular && npm run package-linux
before_deploy:
  - cd build
  - bash ../script/zip.sh
  - npm i -g @angular/cli
  - export RELEASE_PKG_FILE=$(ls *.zip)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  - provider: releases
    api_key:
      secure: NsD7Ppt4T2FerZ7/beTiw6e91dRBdQv31l1DV5pg3nVzm63Hwy56JDGe7c5B5N24BwdXMd1mHGBu+wKW4G3ZtgOcefbT0ZMCPLGwPF6ibn1FjO+ye6RzNzS7aVMpmlOvd22BPeTVIubSsdFPbM/T9OF1kDt+aXdhtzlywlYBvJRewcbApEfUyzOZ2i1LfZXao8qWlV8eeDwYul8FLMkvqTdjiM0dia+ZBo+GPbwFQTjcImCbEc2uWPAu3E7IsiUBkF1+CEQTx523TUnTOlomCSNU//YeqUpVnv0HPznMzDux57qtGLZpDIadwykKQHpRbUtXIer8iGlDEdYS0PF4WKVo+skLYz4n9YjfOJfQTcC4760UhurnYx9oH3TrD+JgHZe7Jx4ol3eGliz7VnuKWopEZNk+LYKPEQEYpniIDyRNZ+9+9OMefC/1FK+wTIlPmrmkh439HHWLHecRCYK3JBHCbZ1BCtstAOv+oBfR9/yaUsyp5JvDRrPi2KWOgpcaqQ0KPpHy4BssTOIWaTbAbYoqltqUTEU8VxkbVRYIisOa9cXeajOjDuLWNRaIJeh9wfOxkQ1SMI8oe+jrdDGWSfM1AF5TNJ2lQOogl6dbyekR2Tj6AEW7mvx05KrIVtgH9dTk/MgQpUHRlw+LK9Y+Q0ZN9rd+seRw146rII3UgiA=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      branch: master
  - provider: releases
    api_key:
      secure: NsD7Ppt4T2FerZ7/beTiw6e91dRBdQv31l1DV5pg3nVzm63Hwy56JDGe7c5B5N24BwdXMd1mHGBu+wKW4G3ZtgOcefbT0ZMCPLGwPF6ibn1FjO+ye6RzNzS7aVMpmlOvd22BPeTVIubSsdFPbM/T9OF1kDt+aXdhtzlywlYBvJRewcbApEfUyzOZ2i1LfZXao8qWlV8eeDwYul8FLMkvqTdjiM0dia+ZBo+GPbwFQTjcImCbEc2uWPAu3E7IsiUBkF1+CEQTx523TUnTOlomCSNU//YeqUpVnv0HPznMzDux57qtGLZpDIadwykKQHpRbUtXIer8iGlDEdYS0PF4WKVo+skLYz4n9YjfOJfQTcC4760UhurnYx9oH3TrD+JgHZe7Jx4ol3eGliz7VnuKWopEZNk+LYKPEQEYpniIDyRNZ+9+9OMefC/1FK+wTIlPmrmkh439HHWLHecRCYK3JBHCbZ1BCtstAOv+oBfR9/yaUsyp5JvDRrPi2KWOgpcaqQ0KPpHy4BssTOIWaTbAbYoqltqUTEU8VxkbVRYIisOa9cXeajOjDuLWNRaIJeh9wfOxkQ1SMI8oe+jrdDGWSfM1AF5TNJ2lQOogl6dbyekR2Tj6AEW7mvx05KrIVtgH9dTk/MgQpUHRlw+LK9Y+Q0ZN9rd+seRw146rII3UgiA=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      tags: true